
C      ######################################################################
C      #################      CAE Assistant Company          ################
C      ##############         www CAEassistant com              #############
C      ###########   Copy right by CAE Assistant Company    ###############
C      ######################################################################
C      ONLY the BUYER  of this package has permission to use its codes.
C	 Any distribution of this subroutine is illegal and will be prosecuted 
C      ######################################################################
C      ######################################################################
C      CAE Assisitant Services: 
C      Toturial Packages,Consultancy,Articles,Q&A,Video Gallery,Online Course
C      ######################################################################
C      Need help with your project? 
C      You can get initial free consultation from (Support CAEassistant com)
C      ######################################################################
      SUBROUTINE UEXPAN(EXPAN,DEXPANDT,TEMP,TIME,DTIME,PREDEF,
     1 DPRED,STATEV,CMNAME,NSTATV,NOEL)
C
      INCLUDE 'ABA_PARAM.INC'
C
      CHARACTER*80 CMNAME
C
      DIMENSION EXPAN(*),DEXPANDT(*),TEMP(2),TIME(2),PREDEF(*),
     1 DPRED(*),STATEV(NSTATV)
C
      REAL*4 CTE1,CTE2,CTE3,CCS1,CCS2,CCS3
C
      CTE1 = 0.5D-6          !Thermal expansion coefficient in fiber's direction
      CTE2 = 35.3D-6         !Thermal expansion coefficient in resin's direction
      CTE3 = 35.3D-6         !Thermal expansion coefficient in resin's direction
C
      CCS1 = -167.D-6        !Chemical shrinkage coefficient in fiber's direction
      CCS2 = -8810.D-6       !Chemical shrinkage coefficient in resin's direction
      CCS3 = -8810.D-6       !Chemical shrinkage coefficient in resin's direction
C
      EXPAN(1) = !Hidden Content Please purchase the full product to access the complete code.  
C      
      DEXPANDT(1) = !Hidden Content Please purchase the full product to access the complete code. 
C
      RETURN
      END
C   
      subroutine usdfld(field,statev,pnewdt,direct,t,celent,time,dtime,
     1 cmname,orname,nfield,nstatv,noel,npt,layer,kspt,kstep,kinc,
     2 ndi,nshr,coord,jmac,jmtyp,matlayo,laccflg)
C
       include 'aba_param.inc'
C
      character*80 cmname,orname
      character*3  flgray(15)
      dimension field(nfield),statev(nstatv),direct(3,3),t(3,3),time(2),
     * coord(*),jmac(*),jmtyp(*)
      dimension array(15),jarray(15)
C
      REAL*4 ALPHA,DADT,DADTT,DE1,DE2,DE3,A1,A2,A3,R,k1,k2,k3,
     +       Dk1DT,Dk2DT,Dk3DT,MINSEC,B,ONE,TEMP1
C
C     STATEV(1) : Degree of Cure
C     STATEV(2) : Rate of Cure
C     STATEV(3) : The Variation in the RATE OF CURE with Respect to Temperature
C      
C     ALPHA : Degree of Cure
C      
C     DADT : Rate of Cure
C     DADTT : Variation of the Rate of Cure with Respect to Temperature
C      
C     DE1,DE2,DE3 :  Activation Energies
C     A1,A2,A3 :  Pre-exponential Constants
C     k1,k2,k3 :  Rate constants
C     Dk1DT,Dk2DT,Dk3DT : Variations of Rate Constants with Respect to Temperature
C      
C     R : Universal Gas Constant
C     RHOR : Resin Density
C     HR : Total Thermal Energy Generated by Reaction
C      
C     MINSEC : Conversion of Minute to Second
C      
C     VF : fiber volume fraction
C     B: Constant Value
C      
C     TEMP1: Current Temperature
C
      R=8.3143
C      
      A1=2.101D9
      A2=-2.014D9
      A3=1.960D5
      DE1=8.07D4
      DE2=7.78D4
      DE3=5.66D4
      B=0.47D0
C      
      ONE=1.D0  
      MINSEC=60.D0
C      
      ALPHA= !Hidden Content Please purchase the full product to access the complete code. 
C      
      IF (kinc .le. 1) THEN
        !Hidden Content Please purchase the full product to access the complete code. 
      END IF
C      
      !Hidden Content Please purchase the full product to access the complete code. 
C      
      IF (ALPHA<=0.3D0) THEN
            k1=A1*EXP(-DE1/R/TEMP1)

            DADT=(k1+k2*ALPHA)*(ONE-ALPHA)*(B-ALPHA)
C
            !Hidden Content Please purchase the full product to access the complete code. 
      ELSE
            k3=A3*EXP(-DE3/R/TEMP1)
            DADT=k3*(ONE-ALPHA)
C
              !Hidden Content Please purchase the full product to access the complete code. 
      ENDIF
C
      STATEV(2)=DADT/MINSEC
      !Hidden Content Please purchase the full product to access the complete code. 
C      
C      
      RETURN
      END
C      
      SUBROUTINE DISP(U,KSTEP,KINC,TIME,NODE,NOEL,JDOF,COORDS)
C
      INCLUDE 'ABA_PARAM.INC'
C
      DIMENSION U(3),TIME(2),COORDS(3)
C
      REAL*4 T,RATE,T1,T2,T3,T4,TEMP0,TEMP1,TEMP2
C      
C     T: Time
C     RATE: Temperature increse per second 
C     T1-T4: Time Points
C     TEMP0-TEMP2: Temperature Points
C      
      T=TIME(1)
      RATE=2.5D0/60.D0
C      
      T1=2184.D0
      T2=5784.D0
      T3=7248.D0
      T4=14448.D0
C      
      TEMP0=298.15D0
      TEMP1=389.15D0
      TEMP2=450.15D0
C      
      IF (T<=T1) THEN
      !Hidden Content Please purchase the full product to access the complete code. 
      ENDIF
C      
      RETURN
      END
C
      SUBROUTINE HETVAL(CMNAME,TEMP,TIME,DTIME,STATEV,FLUX,
     1                  PREDEF,DPRED)
C
      INCLUDE 'ABA_PARAM.INC'
C
      CHARACTER*80 CMNAME
      DIMENSION TEMP(2),STATEV(*),PREDEF(*),TIME(2),FLUX(2),
     1          DPRED(*)
C
      REAL*4 RHOR,ONE,HR,VF, ALPHA
C
C     STATEV(1) : Degree of cure
C     STATEV(2) : Rate of cure
C     STATEV(3) : The variation in the rate of cure with respect to temperature
C     RHOR :  Resin density
C     HR :  Total thermal energy generated by the reaction
C     VF :  Fiber volume fraction
C
      RHOR=1272.D0
      VF=0.52D0
C      
      HR=473.6D3
C      
      ONE=1.D0
      ALPHA = STATEV(1)-STATEV(2)*DTIME
C      
      IF (ALPHA<=0.45D0) THEN
          RHOR=1232.D0+90.D0*(ALPHA)
      ENDIF
C
      FLUX(1)=!Hidden Content Please purchase the full product to access the complete code. 
      !Hidden Content Please purchase the full product to access the complete code. 
C
      RETURN
      END
      SUBROUTINE UMAT(STRESS,STATEV,DDSDDE,SSE,SPD,SCD,
     1 RPL,DDSDDT,DRPLDE,DRPLDT,
     2 STRAN,DSTRAN,TIME,DTIME,TEMP,DTEMP,PREDEF,DPRED,CMNAME,
     3 NDI,NSHR,NTENS,NSTATV,PROPS,NPROPS,COORDS,DROT,PNEWDT,
     4 CELENT,DFGRD0,DFGRD1,NOEL,NPT,LAYER,KSPT,KSTEP,KINC)
C
      INCLUDE 'ABA_PARAM.INC'
C
      CHARACTER*80 CMNAME
      DIMENSION STRESS(NTENS),STATEV(NSTATV),
     1 DDSDDE(NTENS,NTENS),DDSDDT(NTENS),DRPLDE(NTENS),
     2 STRAN(NTENS),DSTRAN(NTENS),TIME(2),PREDEF(1),DPRED(1),
     3 PROPS(NPROPS),COORDS(3),DROT(3,3),DFGRD0(3,3),DFGRD1(3,3)
C
      REAL*8 ALPHA, TEMP1
      REAL*8 C11inf, C12inf, C22inf,C23inf,C44inf,C55inf
      REAL*8 C11u, C12u, C22u,C23u,C44u,C55u
      REAL*8 depsilon(NTENS)
      REAL*8 Tg
C      
      INTEGER Countnum
C      
      !Unrelaxed Modulus
      C11u = 127.4D9
      !Hidden Content: You can get the complete code from our website for free. CAE Assistant com
C     
      !Fully Relaxed Modulus
      C11inf = C11u * 0.14D0
      C12inf = C12u * 0.14D0
      !Hidden Content: You can get the complete code from our website for free. CAE Assistant com
      
C     ALPHA : Degree of cure
C      
      ALPHA = STATEV(1) - STATEV(2) * DTIME / 2.0D0
      TEMP1 = TEMP + DTEMP / 2.0D0
C
      Tg = 10.344D0 + 11.859 * ALPHA + 178.04 * ALPHA * ALPHA + 273.15D0
C      
      DO I=1,NTENS
          DO J=1,NTENS
              DDSDDE(I,J) = 0.0D0
          END DO
      END DO
C      
      IF (TEMP1 >= Tg) THEN
          DDSDDE(1,1) = C11inf
          DDSDDE(1,2) = C12inf
      !Hidden Content: You can get the complete code from our website for free. CAE Assistant com
      END IF
C      
      !Hidden Content: You can get the complete code from our website for free. CAE Assistant com
C
      IF (kinc <= 0) THEN
          STATEV(3+1) = 0.0D0
          STATEV(3+2) = 0.0D0
          STATEV(3+3) = 0.0D0
          STATEV(3+4) = 0.0D0
          STATEV(3+5) = 0.0D0
          STATEV(3+6) = 0.0D0
      END IF
      
C      
      depsilon(1) = DSTRAN(1)
      !Hidden Content: You can get the complete code from our website for free. CAE Assistant com
      
      
      IF (TEMP1 >= Tg) THEN
          STRESS(1) = STRESS(1) + C11inf * depsilon(1) + C12inf * depsilon(2) + 
     *    !Hidden Content: You can get the complete code from our website for free. CAE Assistant com
      END IF
C      
      IF (TEMP1 >= Tg) THEN
          STATEV(3+1) = 0.0D0
          STATEV(3+2) = 0.0D0
          STATEV(3+3) = 0.0D0
          STATEV(3+4) = 0.0D0
          STATEV(3+5) = 0.0D0
          STATEV(3+6) = 0.0D0
      ELSE
      !Hidden Content: You can get the complete code from our website for free. CAE Assistant com
          STATEV(3+5) = (C55u * depsilon(5)) * 0.86D0 + STATEV(3+5)
      !Hidden Content: You can get the complete code from our website for free. CAE Assistant com
      END IF
      RETURN
      END